<?xml version="1.0"?>
<package format="3">
  <name>traj_opt</name>
  <version>0.0.0</version>
  <description>Trajectory optimization for Diff-Planner-PX4.</description>
  <maintainer email="iszhouxin@zju.edu.cn">iszhouxin</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>path_searching</depend>
  <depend>plan_env</depend>
  <depend>rclcpp</depend>
  <depend>traj_utils</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
