<?xml version="1.0"?>
<package format="3">
  <name>selected_points_publisher</name>
  <version>0.1.0</version>
  <description>RViz plugin to select points and publish them in a new topic. (Updated by Xin Zhou)</description>
  <maintainer  email="david.wong@tier4.jp">David Wong</maintainer>
  <maintainer  email="iszhouxin@zju.edu.cn">Xin Zhou</maintainer>
  <license>Apache 2</license>
  <author email="david.wong@tier4.jp">David Wong</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>rviz_rendering</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
